service: blue-spruce-pg-api
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    webpackConfig: 'webpack.config.ts'
    packager: 'yarn'
    includeModules: true
